/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LP03;

import javax.swing.JOptionPane;


public class FrmLP03 extends javax.swing.JFrame {

    /**
     * Creates new form FrmLP03
     */
    public FrmLP03() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnEx1 = new javax.swing.JButton();
        btnEx2 = new javax.swing.JButton();
        btnEx3 = new javax.swing.JButton();
        btnEx4 = new javax.swing.JButton();
        btnEx5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescricao = new javax.swing.JTextArea();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Lista de Exercicios 03");

        btnEx1.setText("1- Números pares");
        btnEx1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEx1MouseMoved(evt);
            }
        });
        btnEx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEx1ActionPerformed(evt);
            }
        });

        btnEx2.setText("2 - Enésimo termo de Fibonacci");
        btnEx2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEx2MouseMoved(evt);
            }
        });
        btnEx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEx2ActionPerformed(evt);
            }
        });

        btnEx3.setText("3- Números primos");
        btnEx3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEx3MouseMoved(evt);
            }
        });
        btnEx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEx3ActionPerformed(evt);
            }
        });

        btnEx4.setText("4- Média Fatec");
        btnEx4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEx4MouseMoved(evt);
            }
        });
        btnEx4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEx4ActionPerformed(evt);
            }
        });

        btnEx5.setText("5- Incremento e limite");
        btnEx5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEx5MouseMoved(evt);
            }
        });
        btnEx5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEx5ActionPerformed(evt);
            }
        });

        textAreaDescricao.setColumns(20);
        textAreaDescricao.setLineWrap(true);
        textAreaDescricao.setRows(5);
        textAreaDescricao.setAutoscrolls(false);
        jScrollPane1.setViewportView(textAreaDescricao);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEx5)
                                    .addComponent(btnEx3)
                                    .addComponent(btnEx4)
                                    .addComponent(btnEx1))
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEx2)
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSair)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEx1)
                        .addGap(26, 26, 26)
                        .addComponent(btnEx2)
                        .addGap(26, 26, 26)
                        .addComponent(btnEx3)
                        .addGap(26, 26, 26)
                        .addComponent(btnEx4)
                        .addGap(26, 26, 26)
                        .addComponent(btnEx5))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEx1ActionPerformed
        LP03_01 ex01 = new LP03_01();
        String valorInicial, valorFinal, pares;
        valorInicial = ex01.lerPrimeiroNum();
        valorFinal = ex01.lerSegundoNum(valorInicial);
        pares = ex01.numerosPares(valorInicial, valorFinal);
        ex01.exibirPares(valorInicial, valorFinal, pares);
    }//GEN-LAST:event_btnEx1ActionPerformed

    private void btnEx1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEx1MouseMoved
        textAreaDescricao.setText(
                "1) Um programa capaz de imprimir todos os números pares em um "
                + "intervalo de números informador pelo usuário;");
    }//GEN-LAST:event_btnEx1MouseMoved

    private void btnEx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEx2ActionPerformed
        LP03_02 ex02 = new LP03_02();
        String termo, sequencia;
        termo = ex02.lerTermo();
        sequencia = ex02.sequenciaFibonacci(termo);
        ex02.exibirSequencia(termo, sequencia);
    }//GEN-LAST:event_btnEx2ActionPerformed

    private void btnEx2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEx2MouseMoved
        textAreaDescricao.setText(
                "2) Um programa que imprima até o “n” termo a seqüência de Fibonacci."
                + " Série:\n 1,1,2,3,5,8,13,21......."
                + "\nPor exemplo, imprimir até o 6º termo: 1, 1, 2, 3, 5, 8");
    }//GEN-LAST:event_btnEx2MouseMoved

    private void btnEx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEx3ActionPerformed
        LP03_03 ex03 = new LP03_03();
        String inicio, fim, primos;
        inicio = ex03.lerInicio();
        fim = ex03.lerFim(inicio);
        primos = ex03.numPrimos(inicio, fim);
        ex03.exibirNumPrimos(inicio, fim, primos);
    }//GEN-LAST:event_btnEx3ActionPerformed

    private void btnEx3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEx3MouseMoved
        textAreaDescricao.setText("3) Um programa capaz de imprimir todos os "
                + "números primos em um intervalo de números informado pelo usuário;");
    }//GEN-LAST:event_btnEx3MouseMoved

    private void btnEx4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEx4ActionPerformed
        LP03_04 ex04 = new LP03_04();
        String p1, p2, trabalho, media;
        p1 = ex04.lerP1();
        p2 = ex04.lerP2(p1);
        trabalho = ex04.lerTrabalho(p1,p2);
        media = ex04.mediaFatec(p1, p2, trabalho);
        ex04.exibirMedia(p1, p2, trabalho, media);
    }//GEN-LAST:event_btnEx4ActionPerformed

    private void btnEx4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEx4MouseMoved
        textAreaDescricao.setText("4) Um programa que calcule a média de uma "
                + "aluno nos moldes da Fatec Zona SUL.");
    }//GEN-LAST:event_btnEx4MouseMoved

    private void btnEx5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEx5ActionPerformed
        LP03_05 ex05 = new LP03_05();
        String limite, salto, sequencia;
        limite = ex05.lerLimite();
        salto = ex05.lerSalto(limite);
        sequencia = ex05.sequencia(limite, salto);
        ex05.exibirSequencia(limite, salto, sequencia);
    }//GEN-LAST:event_btnEx5ActionPerformed

    private void btnEx5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEx5MouseMoved
        textAreaDescricao.setText("5) Criar um programa que leia um número que será"
                + " o limite superior de um intervalo e o incremento. Exibir "
                + "todos os números naturais no intervalo de 0 até esse número."
                + "Suponha que os dois números lidos são maiores que zero. Exemplo:\n"
                + "Limite superior: 20\n"
                + "Incremento: 5\n"
                + "Saída: 0 5 10 15 20");
    }//GEN-LAST:event_btnEx5MouseMoved

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        Object[] opcoes = {"Sim", "Não"};
        int i = JOptionPane.showOptionDialog(null, "Deseja fechar a aplicação?",
                "Sair", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);

        if (i == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLP03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLP03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLP03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLP03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLP03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEx1;
    private javax.swing.JButton btnEx2;
    private javax.swing.JButton btnEx3;
    private javax.swing.JButton btnEx4;
    private javax.swing.JButton btnEx5;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea textAreaDescricao;
    // End of variables declaration//GEN-END:variables
}
