/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projeto_BD.view.Pedido;

import Projeto_BD.control.ClienteControl;
import Projeto_BD.control.PedidoControl;
import Projeto_BD.model.bean.ClienteBEAN;
import Projeto_BD.model.bean.PedidoBEAN;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author claud
 */
public class ConsultarPedido extends javax.swing.JFrame {

    private Integer ID;

    public void visuDataHora() {
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Calendar date = Calendar.getInstance();
        int hora = date.get(Calendar.HOUR_OF_DAY) - 1;
        int min = date.get(Calendar.MINUTE);
        lblDataHora.setText(hora + ":" + min + " - " + formatter.format(date.getTime()));
    }

    public void visuGeral() {
        ClienteBEAN cliBEAN = new ClienteBEAN();
        ClienteControl contCli = new ClienteControl();

        PedidoControl contPed = new PedidoControl();

        List<PedidoBEAN> listaPedido = new ArrayList<>();
        listaPedido = contPed.listar();

        DefaultTableModel tbm = (DefaultTableModel) tblDados.getModel();
        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }

        int i = 0;
        for (PedidoBEAN pedBEAN : listaPedido) {
            tbm.addRow(new String[1]);
            tblDados.setValueAt(pedBEAN.getIdPedido(), i, 0);
            tblDados.setValueAt(pedBEAN.getData_pedido(), i, 1);

            cliBEAN.setIdCliente(pedBEAN.getIdCliente());
            cliBEAN = contCli.consultarID(cliBEAN);

            tblDados.setValueAt(cliBEAN.getIdCliente(), i, 2);
            tblDados.setValueAt(cliBEAN.getNome(), i, 3);
            i++;
        }
    }

    public void visuLista(List<PedidoBEAN> listaDados) {
        ClienteBEAN cliBEAN = new ClienteBEAN();
        ClienteControl contCli = new ClienteControl();

        DefaultTableModel tbm = (DefaultTableModel) tblDados.getModel();
        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        int i = 0;
        for (PedidoBEAN bean : listaDados) {
            tbm.addRow(new String[1]);
            tblDados.setValueAt(bean.getIdPedido(), i, 0);
            tblDados.setValueAt(bean.getData_pedido(), i, 1);
            cliBEAN.setIdCliente(bean.getIdCliente());
            cliBEAN = contCli.consultarID(cliBEAN);
            tblDados.setValueAt(cliBEAN.getIdCliente(), i, 2);
            tblDados.setValueAt(cliBEAN.getNome(), i, 3);
            i++;
        }
    }

    public void visuResult(PedidoBEAN bean) {
        ClienteBEAN cliBEAN = new ClienteBEAN();
        ClienteControl contCli = new ClienteControl();

        DefaultTableModel tbm = (DefaultTableModel) tblDados.getModel();
        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        tbm.addRow(new String[1]);
        tblDados.setValueAt(bean.getIdPedido(), 0, 0);
        tblDados.setValueAt(bean.getData_pedido(), 0, 1);
        cliBEAN.setIdCliente(bean.getIdCliente());
        cliBEAN = contCli.consultarID(cliBEAN);
        tblDados.setValueAt(cliBEAN.getIdCliente(), 0, 2);
        tblDados.setValueAt(cliBEAN.getNome(), 0, 3);
    }

    public ConsultarPedido() {
        initComponents();
        visuDataHora();
        visuGeral();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtData = new javax.swing.JTextField();
        lblOU = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        chkNome = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        chkID = new javax.swing.JCheckBox();
        lblDataHora = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultar Pedido");

        txtData.setEnabled(false);

        lblOU.setText("ou");

        txtID.setEnabled(false);
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText("Status:");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        chkNome.setText("Data do pedido");
        chkNome.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkNomeStateChanged(evt);
            }
        });
        chkNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNomeActionPerformed(evt);
            }
        });
        chkNome.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                chkNomePropertyChange(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Consultar PEDIDO");

        chkID.setText("ID do pedido");
        chkID.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkIDStateChanged(evt);
            }
        });
        chkID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIDActionPerformed(evt);
            }
        });

        lblDataHora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDataHora.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDataHora.setText("Hora - Data");

        tblDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pedido", "Data do pedido", "ID Cliente", "Nome do cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDados.setRowHeight(25);
        jScrollPane2.setViewportView(tblDados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultar)
                            .addComponent(chkNome)
                            .addComponent(chkID))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtID)
                            .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lblOU)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDataHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(lblDataHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultar)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIDKeyTyped

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        PedidoBEAN bean = new PedidoBEAN();
        PedidoControl cont = new PedidoControl();
        try {
            if (chkNome.isSelected() == true) {
                txtID.setText("");
                bean.setData_pedido(txtData.getText());
                List<PedidoBEAN> listaDeDados = new ArrayList<>();
                listaDeDados = cont.consultarData(bean);
                lblStatus.setText(bean.getStatus());
                visuLista(listaDeDados);
            } else if (chkID.isSelected() == true) {
                txtData.setText("");
                bean.setIdPedido(Integer.parseInt(txtID.getText()));
                bean = cont.consultarID(bean);
                lblStatus.setText(bean.getStatus());
                visuResult(bean);
            } else {
                lblStatus.setText("Sem nome ou ID para fazer a consulta.");
                visuGeral();
            }
        } catch (NumberFormatException e) {
            lblStatus.setText("Sem nome ou ID para fazer a consulta.");
        } catch (NullPointerException e) {
            lblStatus.setText("Sem nome ou ID para fazer a consulta.");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        MenuPedido menu = new MenuPedido();
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void chkNomeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkNomeStateChanged
        if (chkNome.isSelected() == true) {
            chkID.setSelected(false);
            txtData.enable(true);
        } else {
            txtData.enable(false);
            txtData.setText(null);
        }
    }//GEN-LAST:event_chkNomeStateChanged

    private void chkNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNomeActionPerformed
        if (chkNome.isSelected() == true) {
            chkID.setSelected(false);
            txtData.enable(true);
        } else {
            txtData.enable(false);
            txtData.setText(null);
        }
    }//GEN-LAST:event_chkNomeActionPerformed

    private void chkNomePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_chkNomePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_chkNomePropertyChange

    private void chkIDStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkIDStateChanged
        if (chkID.isSelected() == true) {
            chkNome.setSelected(false);
            txtID.enable(true);
        } else {
            txtID.enable(false);
            txtID.setText(null);
        }
    }//GEN-LAST:event_chkIDStateChanged

    private void chkIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIDActionPerformed
        if (chkID.isSelected() == true) {
            chkNome.setSelected(false);
            txtID.enable(true);
        } else {
            txtID.enable(false);
            txtID.setText(null);
        }
    }//GEN-LAST:event_chkIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JCheckBox chkID;
    private javax.swing.JCheckBox chkNome;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDataHora;
    private javax.swing.JLabel lblOU;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblDados;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
